USE [master]
GO
/****** Object:  Database [LoanStatusWebAPI.Data]    Script Date: 12/04/2023 07:00:30 ******/
CREATE DATABASE [LoanStatusWebAPI.Data]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LoanStatusWebAPI.Data', FILENAME = N'C:\Users\jnamutebi\LoanStatusWebAPI.Data.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LoanStatusWebAPI.Data_log', FILENAME = N'C:\Users\jnamutebi\LoanStatusWebAPI.Data_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LoanStatusWebAPI.Data].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET ARITHABORT OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET  ENABLE_BROKER 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET  MULTI_USER 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET QUERY_STORE = OFF
GO
USE [LoanStatusWebAPI.Data]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 12/04/2023 07:00:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 12/04/2023 07:00:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AccountNumber] [nvarchar](max) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[Address] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Loan]    Script Date: 12/04/2023 07:00:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Loan](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [int] NOT NULL,
	[DisbursementDate] [datetime2](7) NOT NULL,
	[OutstandingAmount] [decimal](18, 2) NOT NULL,
	[LoanPeriod] [int] NOT NULL,
 CONSTRAINT [PK_Loan] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Logtrails]    Script Date: 12/04/2023 07:00:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Logtrails](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EndPoint] [nvarchar](max) NOT NULL,
	[Status] [nvarchar](max) NOT NULL,
	[Message] [nvarchar](max) NOT NULL,
	[ActionbY] [nvarchar](max) NOT NULL,
	[DateCreated] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Logtrails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 12/04/2023 07:00:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](max) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[Phone] [nvarchar](max) NOT NULL,
	[Permissions] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_Loan_CustomerId]    Script Date: 12/04/2023 07:00:31 ******/
CREATE NONCLUSTERED INDEX [IX_Loan_CustomerId] ON [dbo].[Loan]
(
	[CustomerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Loan] ADD  DEFAULT ((0)) FOR [LoanPeriod]
GO
ALTER TABLE [dbo].[Loan]  WITH CHECK ADD  CONSTRAINT [FK_Loan_Customer_CustomerId] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Loan] CHECK CONSTRAINT [FK_Loan_Customer_CustomerId]
GO
USE [master]
GO
ALTER DATABASE [LoanStatusWebAPI.Data] SET  READ_WRITE 
GO
